name: eaves
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - numpy
  - scipy
  - pandas
  - geopandas
  - shapely
  - pyproj
  - rasterio
  - matplotlib
  - scikit-learn
  - tqdm
  - pytest
  - pip
  - pip:
    - forge3d>=1.23.1
